"""Contrato comum dos otimizadores."""
from abc import ABC, abstractmethod
from typing import Sequence


class RouteOptimizer(ABC):
    @abstractmethod
    def initialize(self, cities, config) -> None: ...
    @abstractmethod
    def step(self) -> None: ...
    @abstractmethod
    def is_finished(self) -> bool: ...
    @abstractmethod
    def get_best_route(self) -> list: ...
    @abstractmethod
    def get_best_fitness(self) -> float: ...
    @abstractmethod
    def get_history(self) -> Sequence[float]: ...
    def get_best_solution(self): return None
